### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by chrisbigelow** [chrisbigelow/soundstand#7]

**Comment by LochandQuay** [comment]
@chrisbigelow 

Looks like all the functionality is fine, just needs more work on styling.

Styling Issues:
- [x] Session form is off-center. Usually this means you need a `transform: translateX(-50%)` somewhere after you've partially centered it by doing a `left: 50%`.
- [x] The form in general need more styling. More whitespace and centering or aligning your items somehow would be a huge improvement.
- [x] I'd prefer the errors stood out by being red instead of being bolded. Also, once errors are displayed, it makes it pretty clear that your session form should be wider.

**Comment by chrisbigelow** [comment]
Fixed styling issues

**Comment by LochandQuay** [comment]
@chrisbigelow 

Looks like it works. I would prefer a little more polished styling, but you can come back to it.
